### ISSUE TITLE
Add icon for marketplace

### ISSUE THREAD

**Issue by Silind** [dzhavat/css-to-mdn#4]
Cool little tool. Very useful :smiley: 
I'd recommend adding an icon / logo for marketplace and when searching in VSCode.
That will make it stand out a bit more.

![example](https://silind-s3.s3.eu-west-2.amazonaws.com/random/css-to-mdn.png)

**Comment by dzhavat** [comment]
Totally agree :)

It wasn’t essential for launching the extension so I postponed it for later. But it’s definitely on something I would like to add.
